image: zenika/alpine-maven

variables:
  MAVEN_CLI_OPTS: ""
  MAVEN_OPTS: "-Dmaven.repo.local=cache/.m2/repository"

cache:
  paths:
    - cache/.m2/repository/

build:
  stage: build
  tags:
    - shared
  script:
    - mvn package
